### ISSUE TITLE
Initial error-testing checklist

### ISSUE THREAD

**Issue by dapritchard** [dapritchard/jira-worklog#7]
Some examples of things to test for:
- [ ] error authenticating to Jira (special case WRT testing)
- [ ] config file doesn't exist
- [ ] config file not in the correct format
- [ ] worklogs file doesn't exist
- [ ] worklogs file not in the correct format
- [ ] checkedin file not in the correct format
- [ ] error reading from Jira
- [ ] error writing to Jira
- [ ] error writing to checkedin
